CREATE TABLE TB_PESSOA (
  ID_PESSOA BIGINT NOT NULL GENERATED ALWAYS
        AS IDENTITY (START WITH 1, INCREMENT BY 1)
        CONSTRAINT PK_PESSOA PRIMARY KEY,
  NM_PESSOA VARCHAR(100) NOT NULL,
  DT_NASCIMENTO DATE NOT NULL,
  VL_TELEFONE VARCHAR(20),
  VL_EMAIL VARCHAR(100),
  DT_CADASTRO TIMESTAMP NOT NULL
);
